### ISSUE TITLE
Check for mpv starting is incorrect for Windows (false negative)

### ISSUE THREAD

**Issue by ctlaltdefeat** [iwalton3/python-mpv-jsonipc#2]
The check done upon initialization of ```MPVProcess``` fails for Windows because no file is created; as a matter of fact the named pipe is available.

**Comment by iwalton3** [comment]
This is the underlying issue for https://github.com/iwalton3/plex-mpv-shim/issues/9. (Which was never properly resolved.) I suspected the issue was a race condition, as trying to debug the issue would lead to results that do not make sense.

~~I am now thinking that the issue may be a race between MPVProcess and MPVInter. Maybe the named pipe fails the exist check in certain conditions.~~

**Comment by iwalton3** [comment]
I think this might actually be the solution. I suspect that checking the file twice in a row might be the reason it was failing. I have strong feelings of superstition with this though, as in the past the only times I've had it fail reliably was when on power saver mode on my other computer.

Could you test this to make sure the fix is consistent?

**Comment by ctlaltdefeat** [comment]
My understanding is that when using named pipes in Windows no files are actually created in the filesystem, so I don't think a check that involves ```os.path.exists``` would work. I'm not sure about that though.

I'm going to sleep now, I'll try to check tomorrow if you have updates.

**Comment by iwalton3** [comment]
The `os.path.exists` has to work the first time to break out of the loop and in testing on Windows 10 the condition is true. The problem was it would then be false on the next check and end up in the error condition. The patch makes it so that cannot happen because the value is saved instead of checked again.

I'm going to test this on my other computer (with power save on) that more reliably produces the issue. I'll release if I can't get the MPVError to throw anymore.

Update: I tested 10 times with and without the patch on my other computer. Without, it failed several times randomly. With the patch it succeeded 10 times in a row.

**Comment by iwalton3** [comment]
The new version has been released. Please open this issue again if it does not resolve the problem.

**Comment by erm3nda** [comment]
I used to launch manually the mpv at exception with popen and worked because named pipe was properly created.
Because not handling the process, I had to use another exception to reload the mpv object.

Seems the problem on the check is still present.
Btw, maybe unrelated, i had problems to use "-" in names, really unexpected.

I am using the last version.

**Comment by iwalton3** [comment]
Please provide exact instructions on how to reproduce this issue, and preferably stack traces.

For the issue with arguments, again please explain exactly what is failing.
